### ISSUE TITLE
If the build process fails, there is no way to rebuild

### ISSUE THREAD

**Issue by perandre** [front/wp-cli-build#1]
I accidently cancelled a build process. After trying to run $ wp build once more, it said all was ok, allthough most of the plugins were missing. So: a way to re-build would be good.

**Comment by fabioneves** [comment]
Re-build, should be just to run wp build again. Paste the build.yml used so I try to replicate.

**Comment by perandre** [comment]
File used:

`core:
   download:
       version: 4.7.2
       locale: en_US
plugins:
    advanced-custom-fields-pro:
        version: 5.5.7
    custom-post-type-ui:
        version: 1.5.2
    disable-comments:
        version: '1.6'
    ninja-forms:
        version: 3.0.27
    polylang:
        version: '2.1'
    sendgrid-email-delivery-simplified:
        version: 1.10.7
    timber-library:
        version: 1.2.1
    user-role-editor:
        version: 4.31.1
    wp-super-cache:
        version: 1.4.9
    wordpress-seo:
        version: 4.2.1
`

**Comment by perandre** [comment]
I solved it by simply cloning the repo again, and running wp build.

**Comment by fabioneves** [comment]
wp package install https://github.com/front/wp-cli-build.git

Test the latest version, it should have fixed all the issues you were having.

**Comment by perandre** [comment]
Fix confirmed – after updating the package with `wp package update`, I can re-run `wp build` and it will continue where it left.
