### ISSUE TITLE
--rebuild parameter: what to expect?

### ISSUE THREAD

**Issue by perandre** [front/wp-cli-build#10]
When using `wp build --rebuild` I wasn't sure what to expect. The warning says: 

> Items will be deleted!

Perhaps the warning message could be more precise, and list exactly what is going to happen (I'm not even sure exactly how it decides what to delete). Also: Depending on what it does, it could be that --clean communicates better after all.

**Comment by fabioneves** [comment]
We can rename the parameter. It'll delete everything listed on build file (plugins/themes).

**Comment by perandre** [comment]
I suggest: 

Items will be deleted! => This will delete and re-download all plugins and themes listed in build.yml

Sure, let's use --clean

**Comment by fabioneves** [comment]
Renamed 'rebuild' with 'clean' and updated the text.
