### ISSUE TITLE
Prevent wp build-generate to overwrite versions set to '*'

### ISSUE THREAD

**Issue by perandre** [front/wp-cli-build#11]
Use case:

After first use of wp build-generate, I edit most of the plugins to use version '*'. Next time I run wp-generate, I want to preserve versions that has an asterix.

Agree? If yes, this should go into the build.yml comment block, too.

**Comment by fabioneves** [comment]
That's already implemented. If it's not working like that, then that's a bug.

**Comment by perandre** [comment]
Hm, not able to get the bug anymore. Closing.
