### ISSUE TITLE
Use asterix * for point updates

### ISSUE THREAD

**Issue by perandre** [front/wp-cli-build#12]
Currently we can't set versions to 4.* and 4.9.*. Both are very useful.

**Comment by fabioneves** [comment]
Implemented version constraints with ~ and ^ operators.

Examples:
- Caret operator: ^1.0 can be read as »every Version within major version 1«.
- Tilde operator: ~1.0.0 can be read as »every version within minor version 1.1. The behaviour of tilde operator depends on whether a patch level version is provided or not. If no patch level is provided, tilde operator behaves like the caret operator: ~1.0 is identical to ^1.0.

**Comment by perandre** [comment]
Ok, so caret is used to grab latest major, and tilde for latest minor. 

1. But is this even how the wp.org works? Is it possible to download a version that is, say, the second latest stable release?
2. Can we still use '*' to simply grab the latest?

cc @SofiaSousa for Readme

**Comment by fabioneves** [comment]
I've implemented it in the way that composer, npm and others do it, it's pretty standard. WP.org don't have any version constraint system in-place, they don't have any kind of packaging system, at least none that I'm aware of.

Yes, * is still used for the latest version.

**Comment by perandre** [comment]
To summarize: You can now use both asterisk, tilde and caret operators. Closing.
