### ISSUE TITLE
WP-cli-build always adds "WP-CLI BUILD BLOCK" to the end of .gitignore file

### ISSUE THREAD

**Issue by foadyousefi** [front/wp-cli-build#14]
When running `wp build-generate`, "WP-CLI BUILD BLOCK" part of .gitignore is added to the end of the .gitignore file, some times this could be issue. 

"WP-CLI BUILD BLOCK" of .gitignore, ignores every thing and then exclude custom stuff from being ignored. But if we have some other custom stuff to exclude, such as README.md file, after running `wp build-generate`, the "WP-CLI BUILD BLOCK" that being added to the end of the file, so ignores README.md again.

Will be nice "wp-cli build" if it could add its custom codes in its existing place in the .gitignore file.

**Comment by fabioneves** [comment]
Fixed by the @florianbepunkt PR #24
