### ISSUE TITLE
--skip-git flag not working

### ISSUE THREAD

**Issue by Shebo** [front/wp-cli-build#16]
The --skip-git flag not working as expected. It seems that the condition check is for --no-gitignore flag, but command line expect --skip-git.
So it becomes that we can't choose to skip the gitignore edit when generating build files.

https://github.com/front/wp-cli-build/blob/9dadd87db2c8f3758a7eb8781b1a5d182714cade/src/Build_Generate_Command.php#L55

**Comment by fabioneves** [comment]
Fixed, closing.
