### ISSUE TITLE
Use this with docker cli image

### ISSUE THREAD

**Issue by florianbepunkt** [front/wp-cli-build#17]
this is not a bug report, but a feature/documentation request:

could you please add information how to add this to the official docker cli image? This plugin would be tremendously helpful in a CI/CD scenario.

I tried to create an image based on the official CI image, but installation of this package fails:

```
FROM wordpress:cli

RUN wp --info

USER root

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

USER www-data

RUN php -d memory_limit=1024M "$(which wp)" package install front/wp-cli-build
```

This produces the following error

```
Warning: Failed to execute git clone --mirror 'git@github.com:front/wp-cli-build.git' '/root/.composer/cache/vcs/git-github.com-front-wp-cli-build.git/'


Error: Package installation failed.
---
Reverted composer.json.
```

**Comment by fabioneves** [comment]
Hello,
That error seems pretty generic. Maybe try running wp-cli with --debug ? Do you know if this docker image contains **git**?

**Comment by florianbepunkt** [comment]
This was a rate limiting error with github. I have docker image that adds wp build package.

```
FROM wordpress:cli

USER root

ENV PHP_INI_MEMORY_LIMIT 1024M
RUN echo 'memory_limit = ${PHP_INI_MEMORY_LIMIT}' > "$PHP_INI_DIR/php.ini"

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

USER www-data

RUN wp package install front/wp-cli-build
```

However running the build command inside CI environmentn gives me

`build: not found`

However all files (build.json, etc.) exists. This is outside the scope of a github issue, but by any chance you have an idea what would cause this?

**Comment by fabioneves** [comment]
What CI solution are you using? Gitlab?

**Comment by florianbepunkt** [comment]
I use circleci

**Comment by florianbepunkt** [comment]
I'm not sure what the error means…like what is not found? the build.json or the command is not found…or…

**Comment by fabioneves** [comment]
I don't think the error is related to wp cli at all. It looks like it's
trying to execute the command build which is not found.

**Comment by florianbepunkt** [comment]
Thank you. Problem seems to be that the wp buuild package is not persisted in the wp cli.
