### ISSUE TITLE
--clean supress confirmation

### ISSUE THREAD

**Issue by florianbepunkt** [front/wp-cli-build#18]
Would it be possible to have an option to supress the confirmation when using --clean? This poses problems in non-interactive environments such as CI workflows.

I can look into adding this feature. Probably the warning could be supressed if --quiet parameter is passed as well.

**Comment by fabioneves** [comment]
I've added the 'yes' parameter to confirm such questions, so if you use wp build --clean --yes, it should skip the question now.

**Comment by florianbepunkt** [comment]
Great, thank you.
