### ISSUE TITLE
Version not respected

### ISSUE THREAD

**Issue by florianbepunkt** [front/wp-cli-build#20]
I encountered another issue using the plugin.

The build.json is parsed correctly, but for each plugin the current version is downloaded.

For example I have the following build.json
```
{
  "core": {
    "download": {
      "version": "5.2.4",
      "locale": "de_DE"
    }
  },
  "plugins": {
    "ewww-image-optimizer": {
      "version": "5.0.0"
    }
  },
  "themes": {
    "twentynineteen": {
      "version": "1.4"
    }
  }
}
```

Running the build command I get the console output
`- Downloading ewww-image-optimizer (5.0.0): done`

But looking at the files, I see that he current version 5.1.1 is downloaded.

**Comment by fabioneves** [comment]
I'm gonna have a look, but probably the version 5.0.0 is not available anymore.

**Comment by florianbepunkt** [comment]
I checked: https://wordpress.org/plugins/ewww-image-optimizer/advanced/ It is in the repo

**Comment by fabioneves** [comment]
I've pushed a fix, update wp-cli-build and let me know if it worked pls

**Comment by florianbepunkt** [comment]
Thanks, I can confirm it works for plugins. Will do some more testing regarding core / themes tomorrow. On a separate note: I saw some params that were renamed or stated in code documentation that do not work (ignore params). I will put together a PR on the weekend to fix this

Will close this, as soon as I can confirm the fix for themes/core.

**Comment by fabioneves** [comment]
Awesome! Thanks

**Comment by florianbepunkt** [comment]
I can confirm, that core and theme versions are resspected as well. Closing this as solved.
