### ISSUE TITLE
Params – question for PR

### ISSUE THREAD

**Issue by florianbepunkt** [front/wp-cli-build#21]
Before putting together the PR there are some points we should discuss. As stated before some of the arguments do not work as expected or have been renamed:

These are:

**wp build**
```
* [--ignore-core]
* : Don't process core
*
* [--ignore-plugins]
* : Don't process plugins
*
* [--ignore-themes]
* : Don't process themes

* [--file=<file>]
* : Specify custom build file (default: build.json)
```

**wp build-generate**
```
* [--output=<file>]
* : Where to output build generation result (yml file)
```

The ignore flags are easy to fix.

Regarding `--file/--output` args, however, there are two issues:

**1. Both share `Utils::get_build_filename`**
Therefore wp build-generate --output is not working. The simplest fix would be if we rename the --output arg to --file

**2. filename !== filepath**
There is some mixup in terminology whether --file refers to a filename or filepath. The description gives the impression of `--file` being a filepath, so I can specify --file=config/sub/config.json. This would fit the usecase, where your build.json resideds in another folder than your wp installation, e. g.

`/root/config/build.json` --> build file
`/root/wp/` --> wordpresss directory

But inside Build_Parse::parse() the file param is treated only as a filename only. In fact the full build filepath is overwritten by

```
// Full Build file path.
$file_path = ( Utils::is_absolute_path( $this->filename ) ) ? $this->filename : realpath( '.' ) . '/' . $this->filename;
// Set specified path with --path argument.
if ( ! empty( WP_CLI::get_runner()->config['path'] ) ) {
  $file_path = WP_CLI::get_runner()->config['path'] . '/' . $this->filename;
**// this scrambles every path given in --file arg**
}

```
This makes a scenario as mentioned above (wp and build.json in seperate folders) impossible

In order to solve this I would propose that the `--wp` path is only used as base path for build.json if no --file arg is specified. This works for all three scenarios I can think of:

1. wp build is called in wordpress root, where both wordpress installation and a build.json exist
`wp build` would result in the build.json path of `./build.json`

2. wp build is called in root folder, but wordpress installation and build.json resided in subdirectory
wp build --path="subdirectory" would result in the build.json path of `./subdirectory/build.json`

3. wp build is called in root folder, but wordpress installation and build.json  resided in two different directories
`wp build --file="config/build.json"` --path="subdirectory" would result in the build.json path of `./config/build.json`

The .gitignore on the contrary should always stay in the wp root folder (path specified by --path). Since you can have multiple .gitignores and nest them in folders, this makes it easy to avoid issues like #14 by having your wordpress folder in a subdirectory.

**Comment by fabioneves** [comment]
First of all, awesome contribution, thanks @florianbepunkt!

As for the mixup in terminology, that's a side effect of when I started wp build being something really simples and then adding multiple options and ideas, that's also why the params got lost with version iterations, a bit of lack of time and planning too :)

I agree with your idea of changing everything `--file` argument, it makes sense and the use case seems appropriate. This options got under the radar since we don't use them that much in the company.. so it was just there until someone used it and detected the problems you found :)

Thanks again!

**Comment by florianbepunkt** [comment]
I fully understand and I appreciate the hard work that went into this plugin. We are working on a fully encapsulated wordpress docker environment that can be managed, tested and deployed automatically via CI. This plugin does a lot of the heavy lifting for us, thank you.

I created a PR for the file handling. Will tackle #14 next, so the gitignore section is replaced at the same spot when you regenerate, so it does not interfere with additional instructions you might have put there.

Feel free to close this if the PR works for you.

**Comment by florianbepunkt** [comment]
Thanks. Closing this.
