### ISSUE TITLE
Make wp build run composer

### ISSUE THREAD

**Issue by perandre** [front/wp-cli-build#3]
I would like to add premium plugins using composer, as described here https://premium.wpmudev.org/docs/getting-started/installing-wpmu-dev-plugins-via-composer/

I suggest `wp build` should also trigger `composer install` (or better: `composer update` if that also works for installing first time).

**Comment by PedroPotango** [comment]
Yes! I would love that! +1

**Comment by perandre** [comment]
I changed my mind; runnig composer by it's own can be useful, and forcing it can cause unexpected things. Closing; re-open if you'd like.
