### ISSUE TITLE
More verbose build-generate success message

### ISSUE THREAD

**Issue by perandre** [front/wp-cli-build#6]
Currently, it says: 

`Generating build file (build.yml), please wait...
Success: YAML file generated.`

I think it more sense to have the output be:

```
Connected to database. Now creating files, please wait ...
Success! Generated files:
- build.yml
- .gitignore
```

**Comment by fabioneves** [comment]
I agree on a more verbose output, also for 'build' command.
The build-generate needs a refactor, it was made as a "handy" solution to save work/time for creating the build file, it needs better code.

**Comment by fabioneves** [comment]
Build generate is now more verbose, closing this.
