### ISSUE TITLE
wp build-generate only adds activated plugins to build.yml

### ISSUE THREAD

**Issue by perandre** [front/wp-cli-build#8]
If you install a bunch of plugins, running `wp build-generate` will not add them all to the build file. Only those that are activated will be listed. 

This might be the best solution, but it can also cause confusion, making people go: Not all plugins are listed in build.yml!

Up for disc.

**Comment by fabioneves** [comment]
There's a switch '--all' to include all the plugins. We can discuss on what should be the default tho.

**Comment by perandre** [comment]
Ah, right! This is useful info for the Readme; please add @SofiaSousa This Issue can be closed after Readme is updated.
