### ISSUE TITLE
Asterix (*) needs to be in quotes for the build file to parse

### ISSUE THREAD

**Issue by perandre** [front/wp-cli-build#9]
Without quotes:

![no quotes](https://user-images.githubusercontent.com/118979/36380837-070e4414-1584-11e8-9116-8a2ae9a2d2e3.png)

With quotes:

![quotes](https://user-images.githubusercontent.com/118979/36380844-0d29bf0e-1584-11e8-8133-c8b267bc00e8.png)

Given that the numeric versions work without quotes, the best solution would make this work for latest/* too, so that quotes are never needed.

**Comment by fabioneves** [comment]
Not a bug, it's following YAML spec, that's why there's a parsing error.

**Comment by perandre** [comment]
Right, but forcing quotes on versions was not possible? What happnes when combining asterix and numbers, like 4.9.*; quotes or not= I'm thinking consistency here; would be good to either use always use quotes or don't use it. 

If that is tricky, perhaps we could start the build file with a comment block, which is good anyhow.

```
# Core, plugins and themes hosted on WordPress.org go here. 
# You can set a fixed version, or use an asterix. Examples: 4.5.1, 4.*, or just '*' to fetch the latest stable version.
# Note: Asterix alone need quotes: '*'
```

**Comment by fabioneves** [comment]
It wasn't possible, the symfony/yaml class, decides what to do with a specific value and then it puts quotes or not, we don't control that. That's one of multiple reasons to use JSON, it's less strict. Versions like 4.9.* are not implement.

**Comment by perandre** [comment]
No problem, we'll just add the suggested comment block. Close issue when that is done.

(But: we need to be able to do the 4.* and 4.9.*; creating new Issue for that.)

**Comment by fabioneves** [comment]
For reference, regarding adding comments to the YAML file, it's not supported by Symfony YAML package.
https://github.com/symfony/symfony/issues/22516
